### ISSUE TITLE
double equals! + others 

### ISSUE THREAD

**Issue by hdrdavies** [kat4/wordkat#16]
https://github.com/kat4/wordkat/blob/master/autocomplete.js#L5

There's a double equals used in this line-  could trip sometimes! Would you consider using triple equals? 

-You codeclimate.js file is pretty jokes. Maybe this is meant to look slightly different? I don't know too much about code climate so I might be wrong. 

-You have a favicon!! How did this not muck up?! Our favicon is ruining us. 

-Inline CSS! Maybe you could put this in a separate file and link it to your HTML (Think Jack mentioned this).

**Comment by mantagen** [comment]
Thanks, done
