### ISSUE TITLE
lots of vars

### ISSUE THREAD

**Issue by hdrdavies** [kat4/wordkat#18]
https://github.com/kat4/wordkat/blob/master/server.js#L3

Lots and lots of vars declared here. You could hide them a little bit by separating them with commas, like so:

var huw = 1,
      kat = 4,
     josh = 2,
    ines  = 16, 

etc. 

-I feel like the if statements could be cleaned up a little bit, as there's a bit of repetition, but I'm not sure I could say how you could do that! Sorry!

**Comment by mantagen** [comment]
thanks, will look into it.

**Comment by hdrdavies** [comment]
Thanks!
